// ---------------------- Auth ---------------------------------------

export const UPDATE_CONFIRM_FORM = 'UPDATE_CONFIRM_FORM';
export const CONFIRM_SIGNUP_REQUEST = 'CONFIRM_SIGNUP_REQUEST';
export const CONFIRM_SIGNUP_SUCCESS = 'CONFIRM_SIGNUP_SUCCESS';
export const CONFIRM_SIGNUP_FAILURE = 'CONFIRM_SIGNUP_FAILURE';
export const CONFIRM_USER_ONLY = 'CONFIRM_USER_ONLY';

export const UPDATE_SIGNUP_FORM = 'UPDATE_SIGNUP_FORM';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const UPDATE_SIGNIN_FORM = 'UPDATE_SIGNIN_FORM';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const FETCH_DB_USER_SUCCESS = 'FETCH_DB_USER_SUCCESS';

export const GET_USER_CREDENTIALS_REQUEST = 'GET_USER_CREDENTIALS_REQUEST';
export const GET_USER_CREDENTIALS_SUCCESS = 'GET_USER_CREDENTIALS_SUCCESS';
export const GET_USER_CREDENTIALS_FAILURE = 'GET_USER_CREDENTIALS_FAILURE';

export const UPLOAD_TO_S3_REQUEST = 'UPLOAD_TO_S3_REQUEST';
export const UPLOAD_TO_S3_SUCCESS = 'UPLOAD_TO_S3_SUCCESS';
export const UPLOAD_TO_S3_FAILURE = 'UPLOAD_TO_S3_FAILURE';
export const ACKNOWLEDGE_SUCCESS = 'ACKNOWLEDGE_SUCCESS';

export const CHECK_AUTHENTICATED_USER_REQUEST = 'CHECK_AUTHENTICATED_USER_REQUEST';
export const CHECK_AUTHENTICATED_USER_SUCCESS = 'CHECK_AUTHENTICATED_USER_SUCCESS';
export const CHECK_AUTHENTICATED_USER_FAILURE = 'CHECK_AUTHENTICATED_USER_FAILURE';

export const CREATE_SIGNUP_ERROR = 'CREATE_SIGNUP_ERROR';
export const CLEAR_SIGNUP_ERROR = 'CLEAR_SIGNUP_ERROR';
export const CLEAR_SIGNIN_ERROR = 'CLEAR_SIGNIN_ERROR';
export const CREATE_SIGNIN_ERROR = 'CREATE_SIGNIN_ERROR';
export const CLEAR_CONFIRMATION_ERROR = 'CLEAR_CONFIRMATION_ERROR';

// --------------------------- Content ------------------------------

export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';

export const FETCH_USER_RECORDINGS_REQUEST = 'FETCH_USER_RECORDINGS_REQUEST';
export const FETCH_USER_RECORDINGS_SUCCESS = 'FETCH_USER_RECORDINGS_SUCCESS';
export const FETCH_USER_RECORDINGS_FAILURE = 'FETCH_USER_RECORDINGS_FAILURE';

export const DELETE_FROM_S3_REQUEST = 'DELETE_FROM_S3_REQUEST';
export const DELETE_FROM_S3_SUCCESS = 'DELETE_FROM_S3_SUCCESS';
export const DELETE_FROM_S3_FAILURE = 'DELETE_FROM_S3_FAILURE';

// --------------------------- User ----------------------------------

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';